version: '2'
services:
    jhipstertmapplication-app:
        image: jhipstertmapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=jhipstertmapplication-couchbase
            - SPRING_COUCHBASE_BUCKET_NAME=jhipsterTMApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertmapplication-couchbase:
        extends:
            file: couchbase.yml
            service: jhipstertmapplication-couchbase
